version: '3.9'
services:
  web:
    build:
      dockerfile: ./Dockerfile
      context: ./
      target: grafana
      args:
        PORT: ${PORT}
    container_name: monitor
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      PORT: ${PORT}
      GF_LOG_LEVEL: ${GF_LOG_LEVEL}
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD=: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_DATABASE_TYPE: ${GF_DATABASE_TYPE}
      GF_DATABASE_HOST: ${GF_DATABASE_HOST}
      GF_DATABASE_NAME: ${GF_DATABASE_NAME}
      GF_DATABASE_USER: ${GF_DATABASE_USER}
      GF_DATABASE_PASSWORD: ${GF_DATABASE_PASSWORD}
      GF_DATABASE_SSL_MODE: ${GF_DATABASE_SSL_MODE}
    ports:
      - '${APP_PORT}:${PORT}'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    extra_hosts:
      - host.docker.internal:host-gateway
volumes:
  grafana_storage: {}